### ISSUE TITLE
amdgpu: radv_amdgpu_cs_query_fence_status failed.

### ISSUE THREAD

**Issue by IcyDefiance** [nice-game/nice-engine#1]
https://github.com/intel/external-mesa/blob/master/src/amd/vulkan/winsys/amdgpu/radv_amdgpu_cs.c#L205

**Comment by umbra-scientia** [comment]
solution: "Just install amdvlk."

radv disclaims itself as "not a conformant vulkan implementation" and "testing use only."
Seems reasonable to simply not support it.
